create table peerfit.club_ready_reservations(
ID SERIAL,
CREATED DATETIME DEFAULT now(),
MODIFIED DATETIME DEFAULT now(),
DATE_KEY DATE NOT NULL,
MEMBER_ID INTEGER,
STUDIO_KEY VARCHAR(50) NOT NULL,
CLASS_TAG VARCHAR(50),
INSTRUCTOR_FULL_NAME VARCHAR(200),
LEVEL INTEGER,
CANCELED BOOLEAN,
RESERVED_FOR DATETIME,
SIGNED_IN_AT DATETIME
);


