create table peerfit.mbo_reservations(
ID SERIAL,
CREATED DATETIME DEFAULT now(),
MODIFIED DATETIME DEFAULT now(),
DATE_KEY DATE NOT NULL,
MEMBER_ID INTEGER,
STUDIO_KEY VARCHAR(50) NOT NULL,
STUDIO_ADDRESS_STREET VARCHAR(200) NOT NULL,
STUDIO_ADDRESS_STATE VARCHAR(2) NOT NULL,
STUDIO_ADDRESS_ZIP VARCHAR(9) NOT NULL,
CLASS_TAG VARCHAR(50),
VIEWED_AT DATETIME,
RESERVED_AT DATETIME,
CANCELED_AT DATETIME,
CLASS_TIME_AT DATETIME,
CHECKED_IN_AT DATETIME
);